//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Item
    {
        public Item()
        {
            this.Properties = new ObservableCollection<Property>();
            this.Lists = new ObservableCollection<List>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string StateInfo { get; set; }
    
        public virtual ObservableCollection<Property> Properties { get; set; }
        public virtual ObservableCollection<List> Lists { get; set; }
    }
}
