//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Property
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PropValue { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
